version: '3.8'

services:
  backend:
    image: harshadj/healthroute-backend:latest // <--- USE IMAGE instead of build
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
    restart: always

  frontend:
    image: harshadj/healthroute-frontend:latest // <--- USE IMAGE instead of build
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
